CREATE OR REPLACE NONEDITIONABLE FUNCTION FORMATA_TELEFONE(TELEFONE  VARCHAR)
RETURN VARCHAR
    IS 
    TELEFONE_FORMATADO VARCHAR(25);
BEGIN
    --RETIRA OS CARACTERES ESPECIAIS
      TELEFONE_FORMATADO :=  REGEXP_REPLACE(TELEFONE,'[^a-zA-Z0-9\s]','');
    --FORMATA O TELEFONE PARA 11 DIGITOS  
      IF LENGTH(TELEFONE_FORMATADO) = 10 THEN
        TELEFONE_FORMATADO :=   SUBSTR(TELEFONE_FORMATADO,1,2) || '9' ||SUBSTR(TELEFONE_FORMATADO,3,10);
      END IF;
    --VALIDA  SE O TELEFONE_FORMATADO POSSUI 11 DIGITOS
      IF LENGTH(TELEFONE_FORMATADO) NOT IN (11) THEN
        RAISE_APPLICATION_ERROR(-20253,'Numero de telefone contém mais carcteres do que o formato (XX) 9XXXX-XXXX (11 digitos),verifique os valores e tente novamente!');
      END IF;
    --CASO TENHA  11 DIGITOS FAZ A FORMATACAO  
      IF LENGTH(TELEFONE_FORMATADO) = 11 THEN
        --SE O PRIMEIRO DIGITO ANTES DO NUMERO DE TELEFONE FOR DIFERENTE DE 9 EXECUTAR UM RAISE CASO CONTRARIO FORMATA O TELEFONE
        IF SUBSTR(TELEFONE_FORMATADO,3,1) <> 9 THEN
           RAISE_APPLICATION_ERROR(-20254,'O primeiro digito antes do telefone dever ser 9,verifique e tente novamente!');
          ELSE
               TELEFONE_FORMATADO :=   '(' ||  SUBSTR(TELEFONE_FORMATADO,1,2) || ') ' ||SUBSTR(TELEFONE_FORMATADO,3,1) || ' '  ||SUBSTR(TELEFONE_FORMATADO,4,4) || '-' ||SUBSTR(TELEFONE_FORMATADO,8,4);
        END IF;

      END IF;

      RETURN TELEFONE_FORMATADO;
END;
